name: pub_quiz
description: A pub quiz game.
version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

workspace:
  - packages/pub_quiz_admin
  - packages/pub_quiz_client
  - packages/pub_quiz_player
  - packages/pub_quiz_server
  - packages/pub_quiz_shared
  - packages/pub_quiz_tv

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
