name: pub_quiz
description: A pub quiz game.
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - packages/pub_quiz_admin
  - packages/pub_quiz_tv
  - packages/pub_quiz_player
  - packages/pub_quiz_shared
  - packages/pub_quiz_server

dependencies:
  dart_flutter_team_lints: ^3.5.2
