name: pub_quiz_server
description: The Serverpod server for the Pub Quiz app.
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  serverpod: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
