name: pub_quiz_server
description: The Serverpod server for the Pub Quiz app.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  serverpod: 2.9.2

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  serverpod_test: 2.9.2
  test: '^1.24.2'

