name: pub_quiz_server
description: The Serverpod server for the Pub Quiz app.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  google_generative_ai: ^0.4.7
  serverpod: 2.9.2

dev_dependencies:
  async: ^2.13.0
  dart_flutter_team_lints: ^3.5.2
  serverpod_test: 2.9.2
  test: '^1.24.2'

