name: pub_quiz_widgets
description: Shared widgets of the TV and Mobile Apps.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.10.0'

flutter:
  uses-material-design: true
  fonts:
    - family: Google Sans Flex
      fonts:
        - asset: fonts/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  pub_quiz_shared:
    path: ../pub_quiz_shared

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
