name: pub_quiz_admin
description: The admin panel for the Pub Quiz, built with Jaspr.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0
  pub_quiz_shared:
    path: ../pub_quiz_shared

dev_dependencies:
  build_runner: ^2.6.0
  dart_flutter_team_lints: ^3.5.2
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.5.1
  jaspr_web_compilers: ^4.3.2+1

jaspr:
  mode: client
