name: pub_quiz_shared
description: 'Shared logic for the Pub Quiz app.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
