name: pub_quiz_shared
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
