name: pub_quiz_player
description: The Flutter app for players of the Pub Quiz.
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.10.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  pub_quiz_shared:
    path: ../pub_quiz_shared
  serverpod_flutter: ^2.9.2

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
