name: pub_quiz_player
description: The Flutter app for players of the Pub Quiz.
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.10.0'

resolution: workspace

dependencies:
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  pub_quiz_shared:
    path: ../pub_quiz_shared
  serverpod_flutter: ^2.9.2
  shared_preferences: ^2.5.3

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  fake_cloud_firestore: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
