name: pub_quiz_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  serverpod_client: 2.9.2
  args: ^2.7.0
  collection: ^1.19.1
dev_dependencies:
  test: ^1.26.3
