name: pub_quiz_tv
description: The TV display for the Pub Quiz, built with Flutter.
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  uses-material-design: true

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  pub_quiz_shared: any
  pub_quiz_widgets: any
  serverpod_flutter: ^2.9.2

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
